export class Resources {
    static readonly TEXTURE_TAG_SHIP = "TEXTURE_TAG_SHIP";
    static readonly TEXTURE_TAG_MISSILE = "TEXTURE_TAG_MISSILE";
    static readonly TEXTURE_TAG_SIMPLE_ENEMY = "TEXTURE_TAG_SIMPLE_ENEMY";
    static readonly TEXTURE_TAG_SHOOTING_ENEMY = "TEXTURE_TAG_SHOOTING_ENEMY";
    static readonly TEXTURE_TAG_MOVING_ENEMY = "TEXTURE_TAG_MOVING_ENEMY";
}
